services:
  - type: web
    name: Looking_for_something
    env: ruby
    buildCommand: |
      bundle install
      RAILS_ENV=production bundle exec rails assets:precompile
      RAILS_ENV=production bundle exec rails assets:clean
    startCommand: bundle exec rails db:migrate && bundle exec puma -t 5:5 -p $PORT
    plan: free
    # releaseCommand: RAILS_ENV=production bundle exec rails db:migrate